FROM openjdk:8-jdk-alpine
EXPOSE 8066
ADD target/Timesheet-spring-boot-core-data-jpa-mvc-REST-1-17.0.war Timesheet-spring-boot-core-data-jpa-mvc-REST-1
ENTRYPOINT ["java","-jar","/timesheet-spring-boot-core-data-jpa-mvc-rest-1-17.0.war"]